### ISSUE TITLE
Create blueprint module - features generator

### ISSUE THREAD

**Issue by miti0** [miti0/mosquito#11]
Blueprint - current state of the market consisting of grid of indicators. State can be used for training AI.

**Comment by dabada83** [comment]
What library are you planning to use in order to implement AI?

**Comment by miti0** [comment]
I'm thinking more towards creating a generic layer so I could easily plug-in libraries like scikit, keras or tpot.

**Comment by miti0** [comment]
done + tested on 2 pairs for 30 days - [6af89b8](https://github.com/miti0/mosquito/commit/6af89b8176a65b112c9bc632771a630e03e160d1)
