### ISSUE TITLE
Paper-wallet: add an option to add a user defined amount (currently using real wallet)

### ISSUE THREAD

**Issue by crack00r** [miti0/mosquito#27]
pls add a option to add  a manual amount of BTC with what he can test, and play

**Comment by miti0** [comment]
In config under [Wallet] there is currency and amount, which should define your wallet currency and amount for backtest and paper. Is this what you have on mind or something else?

**Comment by crack00r** [comment]
it only use it for backtest, paper use real stock

**Comment by miti0** [comment]
fixed: [1324079](https://github.com/miti0/mosquito/commit/132407991cbfc9aa945a3268d847f1100554b821)
