### ISSUE TITLE
Backtest only DGB?

### ISSUE THREAD

**Issue by crack00r** [miti0/mosquito#28]
Sun Jul 30 22:50:00 2017, close:0.000005, | 156103.286385DGB | $: -7.74%, b&h: 0.0%
^Cshutting down and writing final statistics!
Plot: Empty dataframe, nothing to draw!
Couldn't find exchange rate for: DGB

****************************************************
*           Final simulation report:               *
****************************************************
Wallet at Start: | 1.0BTC |
Wallet at End: | 156103.286385DGB |
Strategy result: -100.0%
Buy & Hold: 0.0%
Strategy vs Buy & Hold: -100.0%
Total txn: 1
Simulated (data time): -1 days, 5 hours and 35 minutes
Transactions per hour: -0.05
Simulation run time: 1 hours 51 minutes and 29 seconds

**Comment by miti0** [comment]
Can you please send me that what is in your config.ini under:
[Trade]
pairs = ?

+ what strategy are you using?

**Comment by crack00r** [comment]
```
[General]
# Overall info verbosity from 0-2 (0 - no verbosity)
verbosity = 2

[Trade]
exchange = polo
# List of pairs that should be monitored or 'all' if all pairs should be included in ticker
# pairs = all
pairs = all
# Buffer size in hours (how many hours of data samples we need to save in memory)
buffer_size = 24
# Step interval in minutes
interval = 1
strategy = bumblebee
transaction_fee = 0.25
# Currency towards which the balance will be calculated
root_report_currency = BTC
# Prefetches data from history exchange ticker (Used only for Paper and Live trading)
prefetch = true

[Report]
# Currency which will be plottet
plot_pair = all

# ⋅⋅⋅⋅⋅⋅⋅ Mongo DB ⋅⋅⋅⋅⋅⋅⋅
[MongoDB]
url = localhost
port = 27017
db = mosquito


# ⋅⋅⋅⋅⋅⋅⋅ Exchanges ⋅⋅⋅⋅⋅⋅⋅
[Poloniex]
api_key = 
secret = 
# fillOrKill, immediateOrCancel. (postOnly - not supported yet!)
buy_order_type = immediateOrCancel
# fillOrKill, immediateOrCancel. (postOnly - not supported yet!)
sell_order_type = immediateOrCancel


# ⋅⋅⋅⋅⋅⋅⋅ Backtest ⋅⋅⋅⋅⋅⋅⋅
[Backtest]
# Backtest epoch start datetime
from =
# Backtest epoch end datetime
to =
# Number of history days the simulation should start from
hours = 48


# ⋅⋅⋅⋅⋅⋅⋅ Wallet ⋅⋅⋅⋅⋅⋅⋅
[Wallet]
# Comma separated list of currencies
currency=BTC
# Comma separated list of currency represented values
amount=1

```

**Comment by miti0** [comment]
I can see that you are using bumblebee strategy. This is strategy that is focusing ONLY on 1 pair. You can see that in the __init__ constructor (self.pair = 'BTC_DGB').

Another thing is that if you use only 1 pair of currencies in the strategy (for example BTC_DGB), you can set in config.ini _pairs_ to BTC_DGB. Now the bot will fetch data only for that one pair, and the simulation will be much more faster. 

I have tried to run the simulation with setting pairs=all together with prefetch=true and I can see that it is quite slow. I will investigate this while I will work on the multi-currency strategy (mosquito).
