### ISSUE TITLE
RuntimeWarning

### ISSUE THREAD

**Issue by crack00r** [miti0/mosquito#34]
```
Couldn't find exchange rate for: USDT
Fri Aug  4 08:00:07 2017, close:0.000001, | 0.12286907BTC| 0.00277929USDT | $: 0.0%, b&h: 0.0%
going to sleep for:  28  seconds.
/root/mosquito/strategies/mosquito.py:62: RuntimeWarning:

invalid value encountered in double_scalars

Couldn't find exchange rate for: USDT
Couldn't find exchange rate for: USDT

```

**Comment by miti0** [comment]
please, are you using the default config.sample.ini file? What currencies are you trying to trade?

**Comment by crack00r** [comment]
just only mosquto.py --live
so, default settings

**Comment by miti0** [comment]
Mosquito strategy (especially in dev branch) was ONLY tested as backtest. I'm now testing paper and live modes. 
Sorry for that, I should have written it somewhere more visible.

Bumblebee is the most tested strategy so far, please use that one as a base for your strategies.
