### ISSUE TITLE
Just a Status

### ISSUE THREAD

**Issue by crack00r** [miti0/mosquito#41]
looks good so far, i started live a few min. ago

but maybe add https://github.com/miti0/mosquito/pull/38
ore add a option into config... its better for testing, to just buy a smallamount of btc, so you can spread all over more coins, not all into 1

![screenshot_1](https://user-images.githubusercontent.com/6163329/29401123-3bea4200-8330-11e7-8afd-34d9ad43c42b.png)

**Comment by crack00r** [comment]
i just change strategies/mosquito.py a bit

```
                             TradeState.buy,
                             amount=(round((0.0015 / close_pair_price), 8)),
                             rate=close_pair_price,
                             buy_sell_all=False)
```

**Comment by miti0** [comment]
great,..I want to add the functionality #38 in more generic way (into the config file),...I can take a look at it today/tomorrow.

**Comment by miti0** [comment]
btw I'm also here :) https://gitter.im/mosquito-bot/Lobby

**Comment by miti0** [comment]
thanks for the feedback,...hope you don't mind if I close this :)
