### ISSUE TITLE
Bittrex API deprecated call

### ISSUE THREAD

**Issue by AdityaNayak** [miti0/mosquito#43]
Hi, 
I get this error while running with the latest version of bittrex wrapper 
   ```
 res = self.bittrex.get_ticks(currency_pair, 'fiveMin')
AttributeError: 'Bittrex' object has no attribute 'get_ticks'
```

**Comment by miti0** [comment]
Please can you check if you use following bittrex api [https://github.com/miti0/python-bittrex](https://github.com/miti0/python-bittrex)? I have extended the original bittrex library with get_ticks function.

**Comment by AdityaNayak** [comment]
That removed the get_ticks error. It started generating this though: 

```
Starting simulation: TradeMode.backtest, Strategy: bumblebee
Getting currency data: BTC_DOGE, days left: 1 (got total candles: 288)
Going to prefetch data of size (minutes):  300
Fetching done..
dataset_cnt: 60
Traceback (most recent call last):
  File "mosquito.py", line 35, in <module>
    main(args)
  File "mosquito.py", line 9, in main
    engine.run()
  File "/Users/AdityaNayak/Bots/mosquito/core/engine.py", line 179, in run
    self.actions = self.strategy.calculate(self.look_back, self.wallet)
  File "/Users/AdityaNayak/Bots/mosquito/strategies/bumblebee.py", line 69, in calculate
    obv = talib.OBV(close, volume)
  File "talib/func.pyx", line 9213, in talib.func.OBV (talib/func.c:97907)
Exception: inputs are all NaN
```

**Comment by miti0** [comment]
Thank you for reporting this :). Please can you double check if you have following (Bittrex is using '-' and Poloniex '_')?

- you have the right delimiter of the pair in your config.ini. In your case you should have BTC-DOGE (and not BTC_DOGE)

- in bumblebee strategy, you should have also correct pair delimiter on line 20 (in your case BTC-DOGE).


Btw: I have just now fixed one bug, so please pull the latest develop branch.

**Comment by AdityaNayak** [comment]
Yes, same issue. 

I have pulled your latest develop branch. 
And changed the pairs on all 3 places. 

Also, backtesting should work without adding API keys, correct?

**Comment by miti0** [comment]
yes it should.

Can you come to [gitter](https://gitter.im/mosquito-bot/Lobby),..can help you faster there,...

**Comment by miti0** [comment]
Please, did you do any modifications to the strategy or config.ini? If yes, can you please paste it here?

**Comment by miti0** [comment]
I believe this was fixed,..closing
