### ISSUE TITLE
Feature request : includes the Final simulation report text in the chart generated (plot)

### ISSUE THREAD

**Issue by flamby** [miti0/mosquito#45]
Hi,

Would be great to have the Final simulation report in the chart (lower font at the placement of Simulation report title) for future export to PNG.

Keep the good work!

**Comment by miti0** [comment]
thanks for feedback. You mean that it would be useful to automatically save the report as PNG, instead of HTML?

**Comment by flamby** [comment]
No, i just mean embedding the text like the one below in the chart (replacing the title but w/ lower font size), so that an export to PNG will include the summary.
https://www.dropbox.com/s/j7hkuil7465w9tt/Capture%20d%27%C3%A9cran%202017-08-27%2015.52.17.png?dl=0

Right now, the generated chart are readable immediatly but lacks summary (aggre result) for future reading.

**Comment by miti0** [comment]
adding more simulation info (only place I could find in plotly for en extra text was the title). Something like this?

![plot_with_info](https://user-images.githubusercontent.com/1301154/29753922-68696196-8b7b-11e7-9fc6-c2d7c1e9b42f.png)

**Comment by flamby** [comment]
Yes, exactly. That's perfect. Thus, archiving the PNG output permit to remember the performance. 
In the future, we could embed more text (strategy parameters, etc.), thanks to a QRcode with a lib like this one https://pypi.python.org/pypi/qrcode
I think the limit a QRcode can handle is around 4296 characters. So with a compact representation of all parameters, we could certainly embed all parameters necessary to share to someone the exact mosquito settings just by sending him the PNG ;-)

**Comment by miti0** [comment]
love the idea with QRcode!

**Comment by miti0** [comment]
creating new Qr-code enhancement issue and closing this one.
